/**
 * OmniCost: Enterprise AI & Cloud FinOps Command Center
 * Domain Model & Strict TypeScript Type System (Phase 1)
 * 
 * ============================================================================
 * LEARNING RESOURCES & TYPESCRIPT CONCEPTS USED IN THIS FILE:
 * ============================================================================
 * 1. Discriminated Unions:
 *    https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions
 *    Allows TypeScript to narrow down the specific object shape (CloudResource vs LLMResource)
 *    by checking a shared common property called a discriminator (e.g. `type: 'CLOUD' | 'LLM'`).
 * 
 * 2. Utility Types (Record, Omit, Pick, Readonly):
 *    https://www.typescriptlang.org/docs/handbook/utility-types.html
 *    Built-in TypeScript helpers to transform types cleanly without code duplication.
 * 
 * 3. Union & Literal Types:
 *    https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types
 *    Restricts values to exact string literals (e.g. 'AWS' | 'GCP') for compile-time safety.
 * ============================================================================
 */

/**
 * 1. PROVIDERS & CATEGORIES (Literal Unions)
 * Separates standard cloud providers (AWS, GCP, Azure) from AI/LLM providers (OpenAI, Anthropic, Cohere).
 */
export type CloudProvider = 'AWS' | 'GCP' | 'AZURE';
export type AIProvider = 'OPENAI' | 'ANTHROPIC' | 'COHERE' | 'MISTRAL';
export type Provider = CloudProvider | AIProvider;

/**
 * Lifecycle status of any digital asset managed by OmniCost.
 */
export type ResourceStatus = 'ACTIVE' | 'IDLE' | 'CRITICAL' | 'THROTTLED' | 'TERMINATED';

/**
 * Enterprise Cost Centers for internal financial chargebacks.
 */
export type CostCenter = 'ENGINEERING' | 'DATA_SCIENCE' | 'PRODUCT' | 'MARKETING' | 'RESEARCH';

/**
 * Severity levels for real-time cost runaway alerts.
 */
export type AlertSeverity = 'INFO' | 'WARNING' | 'CRITICAL';

/**
 * Role-Based Access Control (RBAC) roles.
 * - ADMIN: Full access, can pull the "Kill Switch" to terminate resources.
 * - FINOPS_ANALYST: Can view analytics, edit rules, and export data.
 * - VIEWER: Read-only access to charts and tables.
 */
export type RBACRole = 'ADMIN' | 'FINOPS_ANALYST' | 'VIEWER';

/**
 * 2. BASE RESOURCE INTERFACE
 * Standard fields present on every line item in our unified billing engine.
 */
export interface BaseResource {
  id: string;
  name: string;
  provider: Provider;
  status: ResourceStatus;
  costCenter: CostCenter;
  hourlyCost: number;
  totalSpend: number;
  createdAt: string; // ISO 8601 Date String
  region: string;
  tags: Record<string, string>;
}

/**
 * 3. CLOUD INFRASTRUCTURE RESOURCE (Extends BaseResource)
 * Discriminated Union Member 1 (`type: 'CLOUD'`).
 * Represents physical/virtual compute, storage, databases, and network assets.
 */
export interface CloudResource extends BaseResource {
  type: 'CLOUD'; // Discriminator property
  provider: CloudProvider;
  resourceType: 'EC2_COMPUTE' | 'S3_STORAGE' | 'RDS_DATABASE' | 'K8S_NODE' | 'NAT_GATEWAY';
  metrics: {
    cpuUtilization: number; // Percentage (0-100)
    memoryUtilization: number; // Percentage (0-100)
    networkIOMb: number; // Megabytes transferred per hour
    diskReadWriteIOPS: number; // Input/Output operations per second
  };
}

/**
 * 4. AI & LLM RESOURCE (Extends BaseResource)
 * Discriminated Union Member 2 (`type: 'LLM'`).
 * Represents AI autonomous agents, fine-tuned models, and API token billing endpoints.
 */
export interface LLMResource extends BaseResource {
  type: 'LLM'; // Discriminator property
  provider: AIProvider;
  modelName: string; // e.g. 'gpt-4o', 'claude-3-5-sonnet', 'text-embedding-3'
  metrics: {
    promptTokens: number; // Input tokens sent to LLM
    completionTokens: number; // Output tokens generated by LLM
    cachedTokens: number; // Tokens served from prompt cache (saving money!)
    requestsPerHour: number; // API call throughput
    latencyMs: number; // Average response latency in ms
    cacheHitRate: number; // Percentage (0-100) of input tokens cached
  };
}

/**
 * 5. UNIFIED OMNI RESOURCE (Discriminated Union)
 * By checking `resource.type === 'CLOUD'` or `resource.type === 'LLM'`,
 * TypeScript automatically provides full IntelliSense autocomplete for metrics.
 */
export type OmniResource = CloudResource | LLMResource;

/**
 * 6. TELEMETRY & REAL-TIME TICK DATA
 * Payload sent from Web Worker off-thread telemetry stream to main UI thread.
 */
export interface TelemetryTickPayload {
  timestamp: string;
  updates: Array<{
    resourceId: string;
    costTick: number; // Financial cost delta added in this 2-second interval
    newCpu?: number;
    newTokens?: number;
    isSpike: boolean;
  }>;
}

/**
 * 7. REAL-TIME ANOMALY ALERT MODEL
 */
export interface Alert {
  id: string;
  resourceId: string;
  severity: AlertSeverity;
  title: string;
  message: string;
  timestamp: string;
  resolved: boolean;
  ruleTriggered: string;
}

/**
 * 8. ANOMALY RULE CONFIGURATION
 * Custom threshold rule configured by FinOps Analysts.
 */
export interface RuleConfiguration {
  id: string;
  name: string;
  metricTarget: 'COST_SPIKE' | 'IDLE_CPU' | 'TOKEN_BURST' | 'LOW_CACHE_HIT';
  thresholdValue: number; // e.g. Spend > $5.00/tick or CPU < 5%
  severity: AlertSeverity;
  enabled: boolean;
}

/**
 * 9. REMEDIATION & IMMUTABLE AUDIT LOG
 * Recorded whenever a user executes a Kill Switch action.
 */
export type RemediationAction = 'TERMINATE' | 'THROTTLE' | 'RESIZE' | 'ENABLE_CACHING';

export interface AuditLog {
  id: string;
  action: RemediationAction;
  resourceId: string;
  resourceName: string;
  executedBy: string; // User ID or RBAC Role
  timestamp: string;
  reasonCode: string;
  estimatedMonthlySavings: number;
}

/**
 * 10. AI FINOPS RECOMMENDATION MODEL
 * Recommendation Engine output flagging waste reduction opportunities.
 */
export type RecommendationCategory = 'IDLE_CLEANUP' | 'TOKEN_CACHING' | 'RIGHT_SIZING' | 'RESERVED_INSTANCE';

export interface AIRecommendation {
  id: string;
  resourceId: string;
  category: RecommendationCategory;
  title: string;
  description: string;
  potentialMonthlySavings: number;
  confidenceScore: number; // 0 - 100%
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  suggestedAction: RemediationAction;
}